# Generated by Django 4.1.1 on 2022-12-08 03:12

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=100)),
                ("department_id", models.CharField(max_length=100)),
                (
                    "department_school",
                    models.CharField(
                        choices=[
                            (
                                "SCOPE",
                                "School of Computer Science and Engineering-SCOPE",
                            ),
                            ("SAS", "School of Advanced Sciences-SAS"),
                            ("SSL", "School of Social Sciences and Languages-SSL"),
                            ("SENSE", "School of Electronics Engineering-SENSE"),
                            ("SELECT", "School of Electrical Engineering-SELECT"),
                            ("SMEC", "School of Mechanical Engineering-SMEC"),
                            ("SCE", "School of Civil Engineering-SCE"),
                            ("VITBS", "VIT Business School-VITBS"),
                            ("VITSOL", "VIT School of Law-VITSOL"),
                            ("VFIT", "VIT Fashion Institute of Technology-VFIT"),
                            ("Other Organization", "Other Organization"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date_of_creation", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending Approval", "Pending Approval"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        max_length=200,
                    ),
                ),
                ("description", tinymce.models.HTMLField()),
                (
                    "department",
                    models.CharField(
                        choices=[
                            (
                                "Computer Science & Engineering - BCE",
                                "Computer Science & Engineering - BCE",
                            ),
                            (
                                "Computer Science and Engineering with Specialisation in Artificial Intelligence and Machine Learning - BAI",
                                "Computer Science and Engineering with Specialisation in Artificial Intelligence and Machine Learning - BAI",
                            ),
                            (
                                "Computer Science and Engineering with Specialisation in Cyber Physical Systems - BPS",
                                "Computer Science and Engineering with Specialisation in Cyber Physical Systems - BPS",
                            ),
                            (
                                "Computer Science and Engineering with Specialisation in Artificial Intelligence and Robotics - BRS",
                                "Computer Science and Engineering with Specialisation in Artificial Intelligence and Robotics - BRS",
                            ),
                            (
                                "M.Tech. Software Engineering - MIS",
                                "M.Tech. Software Engineering - MIS",
                            ),
                            (
                                "Computer Science and Engineering with Specialisation in Business Analytics - MIA",
                                "Computer Science and Engineering with Specialisation in Business Analytics - MIA",
                            ),
                            ("Unauthorized", "Unauthorized"),
                        ],
                        max_length=200,
                    ),
                ),
                ("admitted_year", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        blank=True, editable=True, populate_from="title", unique=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Program Representative", "Program Representative"),
                            ("Student", "Student"),
                            ("Head of Department", "Head of Department"),
                            ("Unauthorized", "Unauthorized"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("admitted_year", models.CharField(max_length=500, null=True)),
                ("slug", models.SlugField(blank=True)),
                (
                    "department",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
