# Generated by Django 4.1.1 on 2022-10-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Program Representative", "Program Representative"),
                    ("Student", "Student"),
                    ("Head of Department", "Head of Department"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
