# Generated by Django 4.1.1 on 2022-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="slug", field=models.SlugField(blank=True),
        ),
    ]
