# Generated by Django 4.1.1 on 2022-10-03 15:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0003_profile_role_alter_query_department"),
    ]

    operations = [
        migrations.RenameModel(old_name="Query", new_name="RaisedQuery",),
    ]
